class Constants:
    TOOLTIP_BUTTON_FORWARD = "Sonraki medya"
    TOOLTIP_BUTTON_BACK = "Önceki medya"
    TOOLTIP_BUTTON_SLIDESHOW = "Sunumu başlat"
    TOOLTIP_BUTTON_SLIDEWAY = "Sunum ilerleme yönü"
    TOOLTIP_BUTTON_PEOPLE = "Kişiler"
    TOOLTIP_BUTTON_NOTES = "Notlar"
    TOOLTIP_BUTTON_ADD_MEDIA = "Medya Ekleme"
    TOOLTIP_BUTTON_EDIT_MEDIA = "Görüntülenen medyayı düzenle"
    TOOLTIP_BUTTON_DELETE_MEDIA = "Görüntülenen medyayı sil"
    TOOLTIP_BUTTON_FILTER = "Süzgeç"
    TOOLTIP_BUTTON_SAME_DATE_LOCATION = "Aynı tarih ve yerdekiler"
    TOOLTIP_BUTTON_SAME_DATE = "Aynı tarihdekiler"
    TOOLTIP_BUTTON_SAME_LOCATION = "Aynı yerdekiler"
    TOOLTIP_BUTTON_LATEST = "Yeni eklenenler"
    TOOLTIP_BUTTON_OPEN_MEDIA = "Görüntülenen medyayı varsayılan uygulamada aç"
    TOOLTIP_BUTTON_LISTS = "Listeler"
    TOOLTIP_BUTTON_BULK_EDIT = "Seçili medyaları toplu düzenle"
    TOOLTIP_BUTTON_EXPORT = "Seçili medyaları dışa aktar"
    TOOLTIP_BUTTON_TODAY_IN_HISTORY = "Tarihte bugün"
    TOOLTIP_BUTTON_ADD_TO_LIST = "Seçili medyaları bir listeye ekle"
    TOOLTIP_BUTTON_EXPLORE_FORGOTTEN = "Unutulanlardan 100 medya"
    TOOLTIP_BUTTON_SETTINGS = "Uygulama Ayarları"

    TOOLTIP_CLOUD_FAIL = "Bulut bağlantısı sağlanamadı"
    TOOLTIP_CLOUD_SUCCESS = "Bulut bağlantısı etkin"

    TOOLTIP_STORAGE_ON = "Yerel Depolama: Açık"
    TOOLTIP_STORAGE_OFF = "Yerel Depolama: Kapalı"

    SETTINGS = "Ayarlar"
    GROUP_BOX_CLOUD = "Bulut Sistemi"

    LABEL_BUTTON_ADD = "YÜKLENECEK MEDYALARA EKLE"
    LABEL_BUTTON_UPLOAD = "MEDYAYI ALBÜME YÜKLE"
    LABEL_TOPIC = "KONU"
    LABEL_TITLE = "BAŞLIK"
    LABEL_LOCATION = "YER"
    LABEL_DATE = "TARİH"
    LABEL_DATE_EST = "Hassasiyet:"
    DEFAULT_DATE = "GG.AA.YYYY"
    LABEL_DATE_OPTION = "Oto. Doldur:"
    LABEL_RADIO_DATE_FROM_FILENAME = "Addan"
    LABEL_RADIO_DATE_FROM_FILEDATE = "Tarihten"
    LABEL_RADIO_DATE_FIXED = "Sabit"
    LABEL_TAGS = "ETİKETLER"
    LABEL_TAGS_HELP = "Etiketleri virgül ile ayırın:"
    LABEL_NOTES = "NOTLAR"
    LABEL_PEOPLE = "KİŞİLER"

    WINDOW_DIALOG_ASSIGN_PERSON = "Kişiyi Ekle"
    WINDOW_DIALOG_ASSIGN_LOCATION = "Yer Seç"
    
    # Settings Dialog Constants
    SETTINGS_DIALOG_TITLE = "Ayarlar"
    SETTINGS_TAB_GENERAL = "Genel"
    SETTINGS_TAB_STORAGE = "Depolama"
    SETTINGS_TAB_CLOUD = "Bulut"
    
    # General Tab
    SETTINGS_THEME = "Tema:"
    SETTINGS_THEME_LIGHT = "Açık"
    SETTINGS_THEME_DARK = "Koyu"
    SETTINGS_THEME_CLASSIC = "Albüm Klasik"
    SETTINGS_PRIVACY_LIMIT = "Medya Gizlilik Limiti:"
    SETTINGS_LATEST_DURATION = "Son Eklenen Medya Süresi:"
    SETTINGS_LATEST_1WEEK = "Son 1 hafta"
    SETTINGS_LATEST_2WEEKS = "Son 2 hafta"
    SETTINGS_LATEST_1MONTH = "Son 1 ay"
    SETTINGS_LATEST_3MONTHS = "Son 3 ay"
    SETTINGS_LATEST_6MONTHS = "Son 6 ay"
    SETTINGS_LATEST_1YEAR = "Son 1 yıl"
    SETTINGS_INITIAL_INDEX = "Açılıştaki Medya:"
    SETTINGS_INITIAL_BEGINNING = "İlk - En eski -"
    SETTINGS_INITIAL_END = "Son - En yeni -"
    SETTINGS_DELETE_ORIGINAL = "Yüklemeden Sonra Orijinal Dosyayı Sil:"
    
    # Storage Tab
    SETTINGS_LOCAL_STORAGE = "Yerel Depolamayı Etkinleştir:"
    SETTINGS_MEDIA_DIR = "Medya Dizini:"
    SETTINGS_THUMBNAILS_DIR = "Önizleme Dizini:"
    
    # Cloud Tab
    SETTINGS_S3_BUCKET = "S3 Bucket Adı:"
    SETTINGS_CLOUDFRONT_DOMAIN = "CloudFront Alan Adı:"
    SETTINGS_CLOUDFRONT_KEY_ID = "CloudFront Anahtar ID:"
    SETTINGS_CLOUDFRONT_KEY_PATH = "CloudFront Anahtar Yolu:"
    
    # Buttons
    SETTINGS_BUTTON_SAVE = "Kaydet"
    SETTINGS_BUTTON_CANCEL = "İptal"
